### ISSUE TITLE
dissect crashes on empty samples

### ISSUE THREAD

**Issue by dkoppstein** [maxplanck-ie/dissectBCL#98]
Recently we had a case where several samples were empty. This causes dissect to crash in prepMail: 

```
Traceback (most recent call last):
  File "/localenv/pipegrp/anaconda/miniconda3/envs/dissectBCL/bin/dissect", line 10, in <module>
    sys.exit(dissect())
  File "/localenv/pipegrp/anaconda/miniconda3/envs/dissectBCL/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/localenv/pipegrp/anaconda/miniconda3/envs/dissectBCL/lib/python3.10/site-packages/rich_click/rich_command.py", line 19, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "/localenv/pipegrp/anaconda/miniconda3/envs/dissectBCL/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/localenv/pipegrp/anaconda/miniconda3/envs/dissectBCL/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/localenv/pipegrp/anaconda/miniconda3/envs/dissectBCL/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/pipegrp/src/github.com/maxplanck-ie/dissectBCL/src/dissectBCL/dissect.py", line 38, in dissect
    main(config)
  File "/home/pipegrp/src/github.com/maxplanck-ie/dissectBCL/src/dissectBCL/dissect.py", line 150, in main
    subject, _html = drHouse.prepMail()
  File "/home/pipegrp/src/github.com/maxplanck-ie/dissectBCL/src/dissectBCL/classes.py", line 455, in prepMail
    self.contamination[optLis[1]][0],  # %reads contam screen
KeyError: '22L002040'
``

**Comment by WardDeb** [comment]
closed in #100
